version: '2'
services:
  odoo:
    image: 'odoo:latest'
    links:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_PORT_5432_TCP_ADDR=db
      - DB_PORT_5432_TCP_PORT=5432
      - DB_ENV_POSTGRES_USER=odoo
      - DB_ENV_POSTGRES_PASSWORD=odoo
  db:
    image: 'postgres:9.4'
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
